name: canteenlib
description: Library for communication with the czech canteen food ordering system iCanteen
version: 1.0.1
repository: 'https://github.com/hernikplays/canteenlib'
issue_tracker: 'https://github.com/hernikplays/canteenlib/issues'
documentation: 'https://docs.hernikplays.cz'

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  dotenv: ^4.0.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.4
