name: canteenlib
description: Library for communication with the czech canteen food ordering system iCanteen
version: 1.1.4
repository: 'https://git.mnau.xyz/hernik/canteenlib'
issue_tracker: 'https://git.mnau.xyz/hernik/canteenlib/issues'

environment:
  sdk: '>=2.16.1 <4.0.0'

dev_dependencies:
  dotenv: ^4.0.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.4
