name: canteenlib
description: Library for communication with the czech canteen food ordering system iCanteen
version: 3.0.5
repository: "https://github.com/tpkowastaken/canteenlib"
issue_tracker: "https://github.com/tpkowastaken/canteenlib/issues"

environment:
  sdk: ">=2.16.1 <4.0.0"

dev_dependencies:
  dotenv: ^4.0.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^1.1.0
  html: ^0.15.4
