name: canteenlib
description: Knihovna pro komunikaci se stravovacím systémem iCanteen
version: 0.1.0-alpha
repository: 'https://github.com/hernikplays/canteenlib'
issue_tracker: 'https://github.com/hernikplays/canteenlib/issues'

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  dotenv: ^3.0.0
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.4
