# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze --fatal-infos

      # Testing pro jidelna.trebesin.cz
      #- name: Credentials pro jidelna.trebesin.cz
      #  run: |
      #    echo "URL= 'jidelna.trebesin.cz'" > .env
      #    echo "USER= '${{ secrets.USER1 }}'" >> .env
      #    echo "PASS= '${{ secrets.PASS1 }}'" >> .env

      #- name: test pro jidelna.trebesin.cz
      #  run: dart test

      # Testing pro obedy.zs-mat5.cz
      - name: Credentials pro obedy.zs-mat5.cz
        run: |
          echo "URL= 'obedy.zs-mat5.cz'" > .env
          echo "USER= '${{ secrets.USER2 }}'" >> .env
          echo "PASS= '${{ secrets.PASS2 }}'" >> .env

      - name: Test pro obedy.zs-mat5.cz
        run: dart test

      # Testing pro obedy.ss-stavebnikolin.cz
      - name: Test pro obedy.ss-stavebnikolin.cz
        run: |
          echo "URL= 'obedy.ss-stavebnikolin.cz'" > .env
          echo "USER= '${{ secrets.USER3 }}'" >> .env
          echo "PASS= '${{ secrets.PASS3 }}'" >> .env

      - name: Test pro obedy.ss-stavebnikolin.cz
        run: dart test
